In [ ]:
import numpy as np
import random

In [ ]:
def getNextStateandReward(r,c,Action):
  #actions : 0 - North, 1 - East, 2 - South, 3 - West
  NextS_r=-1
  NextS_c=-1
  R=-1
  if (r==0 and Action==0) or (r==3 and Action==2) or (c==0 and Action==3) or (c==3 and Action==1):
      NextState=(r,c)
  else:
    if Action==0:
      NextState=(r-1,c)
    elif Action==1:
      NextState=(r,c+1)
    elif Action==2:
      NextState=(r+1,c)
    elif Action==3:
      NextState=(r,c-1)
  return [NextState,R]

In [ ]:
v=np.ones((4,4))
v[0][0]=0
v[3][3]=0
pi=np.ones((4,4,4))/4
theta=1e-10
stable=False
c=0
while(not stable):
  c+=1
  # print(1)
  # d=0
  print("ITERATION - ",c)
  while(True):
    d=0
    for i in range(4):
      for j in range(4):
        # print(i,j)
        if i==j and(i==0 or i==3):
          continue
        v_cur=v[i][j]
        v1=0
        for action in range(4):
          SNext,R=getNextStateandReward(i,j,action)
          x,y=SNext
          v1+=pi[i][j][action]*(R+v[x][y])
        v[i][j]=v1
        d=max(d,abs(v_cur-v[i][j]))
    # print(d)
    if d<theta:
      break
  print("Policy Evaluation")
  print(v)
  stable=True
  for i in range(4):
    for j in range(4):
      if i==j and(i==0 or i==3):
        continue
      old_action=np.random.choice([0,1,2,3], p=pi[i][j])
      a=[]
      for action in range(4):
        SNext,R=getNextStateandReward(i,j,action)
        x,y=SNext
        a.append(R+v[x][y])
      optAction=np.argmax(a)
      pi[i][j]*=0
      pi[i][j][optAction]=1
      if old_action!=optAction:
        stable=False
  print("Policy Improvement")
  print(np.argmax(pi, axis=2))
  print('')

print("STABLE POLICY")
print("v*")
print(v)
print("pi*")
print(np.argmax(pi, axis=2))

ITERATION -  1
Policy Evaluation
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
Policy Improvement
[[0 3 3 3]
 [0 0 3 2]
 [0 0 2 2]
 [0 1 1 0]]

ITERATION -  2
Policy Evaluation
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Policy Improvement
[[0 3 3 2]
 [0 0 0 2]
 [0 0 1 2]
 [0 1 1 0]]

ITERATION -  3
Policy Evaluation
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Policy Improvement
[[0 3 3 2]
 [0 0 0 2]
 [0 0 1 2]
 [0 1 1 0]]

STABLE POLICY
v*
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
pi*
[[0 3 3 2]
 [0 0 0 2]
 [0 0 1 2]
 [0 1 1 0]]


## VALUE ITERATION

In [ ]:
v=np.ones((4,4))
v[0][0]=0
v[3][3]=0
pi=np.ones((4,4,4))/4
theta=1e-10
stable=False
c=0
#value iteration
print("value Iteration")
while(True):
  d=0
  for i in range(4):
    for j in range(4):
      # print(i,j)
      if i==j and(i==0 or i==3):
        continue
      v_cur=v[i][j]
      v1=[]
      for action in range(4):
        SNext,R=getNextStateandReward(i,j,action)
        x,y=SNext
        v1.append(R+v[x][y])
      v[i][j]=max(v1)
      d=max(d,abs(v_cur-v[i][j]))
  # print(d)
  # print()
  print(v)  
  print("")
  if d<theta:
    break
print(v)
# Optimal Policy
optPolicy=np.zeros((4,4))
for i in range(4):
  for j in range(4):
    # print(i,j)
    if i==j and(i==0 or i==3):
      continue
    v_cur=v[i][j]
    v1=[]
    for action in range(4):
      SNext,R=getNextStateandReward(i,j,action)
      x,y=SNext
      # v1+=pi[i][j][action]*(R+v[x][y])
      v1.append(R+v[x][y])
    optPolicy[i][j]=np.argmax(v1)
    # v[i][j]=v1
    # d=max(d,abs(v_cur-v[i][j]))
print("Optimal Policy") 
print(optPolicy)


value Iteration
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]

[[ 0. -1. -2. -2.]
 [-1. -2. -2. -2.]
 [-2. -2. -2. -1.]
 [-2. -2. -1.  0.]]

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
Optimal Policy
[[0. 3. 3. 2.]
 [0. 0. 0. 2.]
 [0. 0. 1. 2.]
 [0. 1. 1. 0.]]


The bug is handled automatically by the argmax function, it always picks the first argument with the maximum value, so if 1 and 3 are the maximum arguments, it always picks 1.