In [ ]:
import numpy as np
from sympy import Symbol, nsolve
import sympy

In [ ]:
from scipy.optimize import fsolve
import math

## Q2

In [ ]:
CellID={}
c=0
for i in range(5):
  for j in range(5):
    CellID[(i,j)]=c
    c+=1
# print(CellID)
A_pos=(0,1)
B_pos=(0,3)
AR=10
BR=5
Anext_pos=(4,1)
Bnext_pos=(2,3)

In [ ]:
def getNextStateAndReward(Action,curState_r,curState_c):
  r,c=curState_r,curState_c
  curState=(r,c)
  NextState=(-1,-1)
  R=0
  if (r==0 and Action==0) or (r==4 and Action==2) or (c==0 and Action==3) or (c==4 and Action==1):
    R=-1
    NextState=curState
  elif curState==A_pos:
    R=10
    NextState=Anext_pos
  elif curState==B_pos:
    R=5
    NextState=Bnext_pos
  else:
    if Action==0:
      NextState=(r-1,c)
    elif Action==1:
      NextState=(r,c+1)
    elif Action==2:
      NextState=(r+1,c)
    elif Action==3:
      NextState=(r,c-1)
  return [NextState,R]



In [ ]:
Coeff=[[0 for i in range(25)]for j in range(25)]
constants=[0 for i in range(25)]
eqn=0
gamma=0.9
for i in range(5):
  for j in range(5):
    currPos=CellID[(i,j)]
    Coeff[eqn][currPos]=1
    #actions: 0-north 1-east 2-south 3-west
    for action in range(4):
      x=(i,j)
      SNext,R=getNextStateAndReward(action,i,j)
      SNext=CellID[SNext]
      Coeff[eqn][SNext]+=-gamma/4
      constants[eqn]+=R/4
    eqn+=1
ans=np.linalg.solve(Coeff,constants)
# v=[[],[],[],[],[]]
for i in range(5):
  for j in range(5*i,5*i+5):
    print(ans[j],end=" ")
  print("")


2.949639069724436 8.136148535942393 3.9846163758201256 4.707372776012998 1.1528129540907548 
1.296302523384006 2.7045472368468997 1.9923795380917066 1.631737154623907 0.33283666731995737 
-0.0780331704708706 0.595379344123669 0.5341194020055408 0.21957615023714638 -0.52700158794592 
-1.0493516769073405 -0.5145030500541512 -0.43347102353900796 -0.6629609676295437 -1.2565293982597165 
-1.910786222155818 -1.3992368661402148 -1.2831932667174368 -1.47606891790306 -2.0269720384302268 


## Q4

In [ ]:
# v=[]
# for i in range(25):
#   var='v'+str(i)
#   v.append(Symbol(var))

In [ ]:
def func(v):
  # v=v.reshape((5,5))
  # eqns=np.zeros((5,5))
  eqns=np.zeros(25)
  gamma=0.9
  for i in range(5):
    for j in range(5):
      currPos=CellID[(i,j)]
      cur=[]
      #actions: 0-north 1-east 2-south 3-west
      for action in range(4):
        x=(i,j)
        SNext,R=getNextStateAndReward(action,i,j)
        x,y=SNext
        # print(x,y)
        cur.append((R+gamma*v[CellID[(x,y)]]))
      eqns[currPos]=v[currPos]-max(cur)
  return eqns

In [ ]:
v=[20 for j in range(25)]
gamma=0.9
v_star = fsolve(func, v).reshape(5,5)
pi_star=[[-1 for i in range(5)] for j in range(5)]
for i in range(5):
  for j in range(5):
    action_values=np.zeros(4)
    for action in range(4):
      x=(i,j)
      SNext,R=getNextStateAndReward(action,i,j)
      x,y=SNext
      # print(x,y)
      action_values[action]=R+gamma*v_star[x][y]
    pi_star[i][j]=np.argmax(action_values)
print(v_star)
print(pi_star)
# print(root)

[[21.97748529 24.4194281  21.97748529 19.41942809 17.47748528]
 [19.77973676 21.97748529 19.77973676 17.80176308 16.02158678]
 [17.80176308 19.77973676 17.80176307 16.02158677 14.4194281 ]
 [16.02158677 17.80176308 16.02158677 14.4194281  12.97748529]
 [14.4194281  16.02158677 14.41942809 12.97748528 11.67973675]]
[[1, 1, 3, 1, 3], [0, 0, 0, 3, 3], [0, 0, 3, 0, 0], [0, 0, 3, 3, 0], [0, 0, 3, 0, 0]]
